version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_TEST=varun
    ports:
      - "8080:80"
    # environment:
    #   - REACT_TEST=varun
    #   - CHOKIDAR_USEPOLLING=true
    
    