FROM node as build

WORKDIR /app

COPY ./package*.json .

RUN npm install

COPY . .

ARG REACT_TEST
ENV REACT_TEST=${REACT_TEST}

RUN npm run build 

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
